media:
  - name: images
    label: Images
    input: src/images
    output: ../images


content:
  - name: globals
    label: Global Settings
    type: file
    path: src/content/globals.json
    format: json
    fields:
      - name: general
        label: General
        type: object
        list:
          min: 1
          max: 1
          collapsible:
            summary: General
        fields:
          - name: siteTitle
            label: Site Title
            type: string
            required: true
          - name: siteDescription
            label: Site Description
            type: string
            required: true
          - name: siteImage
            label: Site Image (1200x630)
            type: image
            required: true

      - name: footer
        label: Footer
        type: object
        list:
          min: 1
          max: 1
          collapsible:
            summary: Footer
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: contact
            label: Contact
            type: text
            required: true
          - name: links
            label: Internal Links
            type: object
            list:
              min: 1
              max: 2
              collapsible:
                summary: Link
            fields:
              - name: link
                label: Link
                type: reference
                required: true
                options:
                  collection: generic
                  search: 'fields.slug,fields.title'
                  value: '{slug}'
                  label: '{title} (/{slug})'

      - name: page404
        label: 404 Page
        type: object
        list:
          min: 1
          max: 1
          collapsible:
            summary: 404 Page
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: subline
            label: Subline
            type: string
            required: true
          - name: linkText
            label: Back Home Link Text
            type: string
            required: true

  - name: home
    label: Home Page
    type: file
    path: src/content/pageHome.md
    fields:
      - name: title
        label: Title (Meta)
        type: string
        required: false

  - name: generic
    label: Generic Pages
    type: collection
    path: src/content/pagesGeneric
    filename: '{primary}.md'
    view:
      fields: [ slug, title ]
    fields:
      - name: slug
        label: Slug (Meta)
        type: string
        required: true
      - name: title
        label: Title (Meta)
        type: string
        required: true
      - name: sections
        label: Page Sections
        type: object
        list:
          min: 1
          collapsible:
            summary: Section
        fields:
          - name: modules
            label: Modules
            type: block
            blockKey: type
            list:
              min: 1
              collapsible:
                summary: 'Module {index}'
            blocks:
              - name: moduleTitle
                label: Title (Heading 1)
                component: moduleTitle
              - name: moduleRichText
                label: Rich-Text
                component: moduleRichText


components:
  moduleTitle:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true

  moduleRichText:
    type: object
    fields:
      - name: content
        label: Content
        type: rich-text
        required: true

  utilImage:
    type: object
    fields:
      - name: image
        label: Image
        type: image
        required: true
      - name: alt
        label: Alt-Text
        type: string
        required: true